spring.application.name=playgroundapi
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=playground;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.default_schema=dbo
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.main.web-application-type=servlet
server.port=8081

# ==========================================
# CẤU HÌNH GỬI EMAIL (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Điền email của bạn (email dùng để gửi mã cho khách)
spring.mail.username=khanhvynguyen200104@gmail.com 
# Điền MẬT KHẨU ỨNG DỤNG (16 ký tự, không chứa dấu cách)
spring.mail.password=elitpoqomqbtyccp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# CẤU HÌNH JWT
# ==========================================
app.jwt.secret=mySuperSecretKeyForJWTTokenGenerationWith32Characters!
app.jwt.expiration=86400000

spring.mail.properties.mail.debug=true


